### PR TITLE
Sign up links work.

### PR DESCRIPTION
**Pull request by Rishi556**
The sign up link takes you to the steemit signup page instead of resulting in errors.

### CODE REVIEW

**Comment by Kennybll** [comment]
@Rishi556 Thanks so much. I wouldn't have caught that! Trying posting on Utopian for a bug fix, and see if they accept it :) Post the link and I'll upvote.

**Comment by gktown** [comment]
Good catch @Rishi556!

**Comment by Rishi556** [comment]
@Kennybll They probably won't accept it, such a small thing I don't think that its enough to be accepted. I'll try and help out with the little bit of web skills I have. Maybe one of those can be submitted.

**Comment by Kennybll** [comment]
Okay thanks though.

**Pull request merged**
